default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
   url: <%= ENV['DEVELOPMENT_DATABASE_URL'] %>

test:
  <<: *default
   url: <%= ENV['TEST_DATABASE_URL'] %>

production:
  <<: *default
  database: Melhores_Pratos_production
  username: Melhores_Pratos
  password: <%= ENV['MELHORES_PRATOS_DATABASE_PASSWORD'] %>
